#!/usr/bin/env python3
"""Fixture-gateway helper for F2 direct-send integration tests (`HMP_V1.md` §7a, T-N015/T-N016).

Builds on `build_fixture.py`'s OFFLINE build (`--build <label> --out <dir>`, run unmodified as a
subprocess -- exactly like `server/tests/integration/test_reads_fixture.py`'s own `_build()`
helper; this module never imports `build_fixture.py`, so nothing here can regress F1's own fixture
tests) and ADDS, without touching that module or its output format:

  - a canonical "Bot Chat" session per profile (`fixture_seed.py seed-session --title "Bot Chat"
    --hidden`, already supports both flags -- no `fixture_seed.py` change needed);
  - `platforms.api_server` enabled on the DEFAULT profile's own `config.yaml`, bound to
    `127.0.0.1` on a fresh free port, with a synthetic >=16-char key inline (`extra.key` --
    `bridge.direct_send_endpoint`'s own DEFAULT-profile precedence, review round 2 should-fix);
  - a deterministic loopback model: the Hermes source tree's OWN e2e fixture,
    `tests/fakes/fake_llm_provider.py` (a real, stdlib-only HTTP server speaking the OpenAI Chat
    Completions wire format), loaded directly from the target BUILD's own `src_dir` via
    `importlib` (never a real provider, never a real network call) and run IN-PROCESS as a
    context manager, so every "reply" this suite ever sees is exactly `default_text` -- fully
    deterministic, per this task's own requirement.

This module owns its OWN gateway `--serve` equivalent (`start_gateway`, mirroring
`build_fixture.py`'s `serve_instances` for the HMP listener alone) rather than calling
`build_fixture.py --serve`: that function REWRITES `config.yaml` from scratch on every serve
(`_write_config_yaml(paths, profile_names, port=port)`) and would silently discard the
api_server/model blocks this module just wrote. One fixture gateway runs at a time (host load,
mirroring `test_reads_fixture.py`'s own convention) -- callers are responsible for not starting a
second one concurrently.

Everything here is additive test tooling: `fixture_seed.py`/`fixture_pairing_cli.py` are called
unmodified, through the SAME `_fixture_common.py` helpers `build_fixture.py` itself uses.
"""

from __future__ import annotations

import importlib.util
import json
import os
import secrets
import socket
import subprocess
import sys
import time
from pathlib import Path
from types import ModuleType
from typing import Any

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

import _fixture_common as fc  # noqa: E402

FIXTURE_SEED = THIS_DIR / "fixture_seed.py"
FIXTURE_PAIRING_CLI = THIS_DIR / "fixture_pairing_cli.py"
# Fixture tooling may be invoked without pytest's server pythonpath configuration.
if str(fc.SERVER_DIR) not in sys.path:
    sys.path.insert(0, str(fc.SERVER_DIR))

BUILD_FIXTURE = THIS_DIR / "build_fixture.py"

# CS-22-style scannable prefix (mirrors `fixtures/f1/instances.yaml`'s own `label_prefix`
# discipline): a synthetic API key generated by this module always starts with this literal, so
# `tools/ci/scan_logs.py`/`private_scan_synthetic.txt`-style tooling can recognize it as fixture
# material on sight, never a real secret.
SYNTHETIC_KEY_PREFIX = "f1-fixture-apikey-"

# The canonical title `bridge.py`'s `_CANONICAL_BOT_CHAT_TITLE` selects (HMP_V1.md §7a DS-4(2)).
BOT_CHAT_TITLE = "Bot Chat"


def synthetic_api_key() -> str:
    """A clearly-synthetic, well-over-16-char `API_SERVER_KEY` (review round 2 should-fix's
    `_has_usable_secret` floor is 16; this is 18 + 24 hex chars)."""
    return SYNTHETIC_KEY_PREFIX + secrets.token_hex(12)


# --------------------------------------------------------------------------------------------------
# The deterministic loopback model (`tests/fakes/fake_llm_provider.py`, loaded from the BUILD).
# --------------------------------------------------------------------------------------------------


def load_fake_llm_provider(build: fc.BuildInfo) -> ModuleType:
    """Loads the target build's OWN `tests/fakes/fake_llm_provider.py` by file path (never a
    package import -- this module lives inside the Hermes source tree, not on this process's own
    `sys.path`, and different extracted builds must never shadow each other's copy in
    `sys.modules`). It is pure standard library (`http.server`, `threading`, `dataclasses`), so it
    imports cleanly in THIS process without needing the build's own venv or any of its
    dependencies."""
    path = build.src_dir / "tests" / "fakes" / "fake_llm_provider.py"
    if not path.is_file():
        raise fc.FixtureSafetyError(
            f"{path} not found -- this build's source tree has no e2e fake-LLM fixture "
            "(tests/fakes/fake_llm_provider.py); direct-send fixture tests need it for a "
            "deterministic model."
        )
    module_name = f"_hmp_fixture_fake_llm_provider_{build.label}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # `dataclass` (used throughout this file) resolves string annotations by looking its own
    # module up in `sys.modules[cls.__module__]` -- it must be registered there BEFORE
    # `exec_module` runs the class bodies, or that lookup raises.
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------------------------------
# config.yaml: api_server + model, written AFTER the offline build, never touched again by
# `build_fixture.py` (this module does its own `--serve` equivalent below).
# --------------------------------------------------------------------------------------------------


def write_direct_send_config(
    paths: fc.InstancePaths,
    profile_names: tuple[str, ...],
    *,
    hmp_port: int,
    api_server_port: int,
    api_key: str,
    model_base_url: str,
    named_profile_keys: dict[str, str] | None = None,
    direct_send_enabled: bool = True,
    owner_device_ids: tuple[str, ...] = (),
    api_server_host: str = "127.0.0.1",
) -> None:
    """Rewrites the instance's own `config.yaml` (the SAME shape `build_fixture.py`'s
    `_write_config_yaml` writes, plus the new blocks) and appends a matching `model:` block to
    every profile's own `config.yaml` (mirroring how that same profile config already duplicates
    `gateway.multiplex_profiles: true` -- profile-scoped config does not inherit the model block
    from the home level in every build, so this module writes it in both places defensively).

    Every entry in `profile_names` is a `hermes profile create`d, NAMED profile -- a real,
    multiplexed Hermes gateway ALWAYS also serves its own built-in, unconfigured `"default"`
    profile FIRST (`served_profile_names()`, empirically confirmed against a live `stock-base`
    gateway's own `/hmp/v1/bots` roster: `[{"profile":"default",...}, {"profile":"f1-alpha",...},
    ...]`), so none of `fixtures/f1/instances.yaml`'s own profiles is ever `bridge.py`'s own
    "default" (`served[0]`) -- every one of them needs its OWN scoped `API_SERVER_KEY`
    (`.env`, review round 2 should-fix's NAMED-profile precedence), never `extra.key`. The
    DEFAULT-profile `extra.key` precedence itself has full unit coverage instead
    (`tests/unit/test_bridge.py::test_direct_send_endpoint_default_profile_prefers_extras_inline_key`).
    `api_key` here is `profile_names[0]`'s (the suite's primary target, `f1-alpha`) own scoped
    key; `named_profile_keys` covers any OTHER profile a test also needs one for (e.g. `f1-empty`,
    for the `no_bot_chat` case).

    `direct_send_enabled` (default `True`, unlike Hermes's own OD-F14/OD-F15 default -- this is
    TEST fixture wiring, not the real default) writes `platforms.hmp.extra.direct_send.enabled`;
    a test that specifically exercises the flag being off calls this again with `False` (review
    round 2 should-fix: the flag is re-read fresh per request, `adapter.py`'s
    `_read_direct_send_enabled` closure, so flipping it here and re-sending takes effect on the
    very next request -- no gateway restart needed)."""
    lines = [
        "plugins:\n",
        '  enabled: ["hmp"]\n',
        "gateway:\n",
        "  multiplex_profiles: true\n",
        "  profile_routes:\n",
    ]
    for name in profile_names:
        lines += [
            f'    - name: "{name}-route"\n',
            '      platform: "hmp"\n',
            f'      profile: "{name}"\n',
            f'      guild_id: "{name}"\n',
        ]
    lines += [
        "  platforms:\n",
        "    hmp:\n",
        "      enabled: true\n",
        "      extra:\n",
        '        bind: "127.0.0.1"\n',
        f"        port: {hmp_port}\n",
        f"        owner_device_ids: {json.dumps(list(owner_device_ids))}\n",
        "        direct_send:\n",
        f"          enabled: {'true' if direct_send_enabled else 'false'}\n",
        "    api_server:\n",
        "      enabled: true\n",
        "      extra:\n",
        f'        host: "{api_server_host}"\n',
        f"        port: {api_server_port}\n",
        f'        key: "{api_key}"\n',
    ]
    model_block = [
        "model:\n",
        "  provider: custom\n",
        f"  base_url: {model_base_url}\n",
        f"  default: {_FAKE_MODEL_ID}\n",
        "  context_length: 128000\n",
        "agent:\n",
        "  api_max_retries: 1\n",
    ]
    (paths.home / "config.yaml").write_text("".join(lines + model_block), encoding="utf-8")
    (paths.home / ".env").write_text("OPENAI_API_KEY=sk-fixture-fake\n", encoding="utf-8")
    # `bridge.direct_send_endpoint`'s `api_server_extra()`/`scoped_api_server_key()` calls run
    # INSIDE `profile_runtime_scope(profile_home)` for EVERY profile (`bridge.py`'s `home = self.
    # _profile_home(profile)` is unconditional) -- and a profile-scoped `load_gateway_config()`
    # reads that profile's OWN `config.yaml`, with NO automatic inheritance from the instance
    # home's copy (empirically confirmed against a live `stock-base` gateway; mirrors the exact
    # reason `build_fixture.py` already duplicates `gateway.multiplex_profiles: true` at both
    # levels). Every profile therefore needs its own copy of the `platforms.api_server.extra`
    # block (host/port only -- `key` never goes here; see the docstring above).
    for name in profile_names:
        profile_cfg = paths.home / "profiles" / name / "config.yaml"
        profile_lines = [
            "gateway:\n",
            "  multiplex_profiles: true\n",
            "  platforms:\n",
            "    api_server:\n",
            "      enabled: true\n",
            "      extra:\n",
            f'        host: "{api_server_host}"\n',
            f"        port: {api_server_port}\n",
        ]
        profile_cfg.write_text("".join(profile_lines + model_block), encoding="utf-8")
    all_keys = {profile_names[0]: api_key, **(named_profile_keys or {})}
    write_named_profile_keys(paths, all_keys)


def write_named_profile_keys(paths: fc.InstancePaths, named_profile_keys: dict[str, str]) -> None:
    """A NAMED (non-default) profile's own `API_SERVER_KEY`, via that profile's own `.env`
    (`profiles/<name>/.env`) -- `bridge.direct_send_endpoint` never reads a named profile's
    `extra.key` (review round 2 should-fix: only the DEFAULT profile does), only its own scoped
    secret, exactly mirroring `api_server.py`'s own `_expected_api_key` precedence for a non-
    default profile. Written (or re-written) independently of `write_direct_send_config`'s own
    call, so a test can add a key for a profile it did not know about at fixture-build time."""
    for name, key in named_profile_keys.items():
        profile_dir = paths.home / "profiles" / name
        profile_dir.mkdir(parents=True, exist_ok=True)
        (profile_dir / ".env").write_text(f"API_SERVER_KEY={key}\n", encoding="utf-8")


_FAKE_MODEL_ID = "fake-model"  # `tests.fakes.fake_llm_provider.MODEL_ID`, mirrored as a literal
# (never imported at module scope -- the module itself is loaded lazily, per build, above).


# --------------------------------------------------------------------------------------------------
# The canonical "Bot Chat" (DS-4(2)): title exactly "Bot Chat", hidden, at least one row so
# `head_message_id` is a real int (`expected_head: null` is `400 bad_request`, DS-1 -- a brand-new,
# zero-message Bot Chat cannot be targeted by this route at all; out of scope for this fixture,
# which always seeds at least one exchange).
# --------------------------------------------------------------------------------------------------


def seed_bot_chat(
    build: fc.BuildInfo,
    paths: fc.InstancePaths,
    profile: str,
    session_id: str,
    *,
    messages: list[dict[str, str]] | None = None,
) -> None:
    messages = messages if messages is not None else [
        {"role": "user", "content": "fixture seed: hello"},
        {"role": "assistant", "content": "fixture seed: hi there"},
    ]
    tmp_dir = paths.out_dir / "direct_send_seed"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    messages_file = tmp_dir / f"{profile}-{session_id}-bot-chat.json"
    messages_file.write_text(json.dumps(messages), encoding="utf-8")
    fc.run_seed_script(
        build,
        FIXTURE_SEED,
        "seed-session",
        "--home", str(paths.home),
        "--profile", profile,
        "--session-id", session_id,
        "--source", "desktop",
        "--title", BOT_CHAT_TITLE,
        "--hidden",
        "--messages-file", str(messages_file),
    )


# --------------------------------------------------------------------------------------------------
# The gateway process itself (mirrors `build_fixture.serve_instances`' HMP-listener spawn, minus
# the reference-device pairing this module's own tests do differently -- see the test module).
# --------------------------------------------------------------------------------------------------


def wait_for_port(port: int, *, timeout: float) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            try:
                s.connect(("127.0.0.1", port))
            except OSError:
                time.sleep(0.5)
                continue
            return True
    return False


def start_gateway(
    build: fc.BuildInfo, paths: fc.InstancePaths, *, log_path: Path
) -> subprocess.Popen[bytes]:
    fc.assert_instance_paths_safe(paths)
    hermes_bin = build.venv_python.parent / "hermes"
    env = fc.clean_hermes_env(
        extra={"HERMES_HOME": str(paths.home), "XDG_STATE_HOME": str(paths.xdg_state)}
    )
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = log_path.open("w", encoding="utf-8")
    return subprocess.Popen(
        [str(hermes_bin), "gateway", "run", "--force"],
        env=env, stdout=log_file, stderr=subprocess.STDOUT,
    )


def stop_gateway(proc: subprocess.Popen[bytes]) -> None:
    if proc.poll() is None:
        proc.terminate()
    try:
        proc.wait(timeout=15)
    except Exception:
        proc.kill()
        proc.wait(timeout=5)


def start_lease_holder(
    build: fc.BuildInfo,
    paths: fc.InstancePaths,
    *,
    profile: str,
    session_id: str,
    desktop_held: bool = False,
) -> subprocess.Popen[str]:
    """Starts `fixture_seed.py acquire-lease` as a BACKGROUND process that holds the lease for as
    long as it stays alive (see that command's own docstring for why it must not exit). Blocks
    briefly here only to confirm the one JSON result line, so a caller never races the lease's own
    acquisition. The caller is responsible for terminating the returned process once the test no
    longer wants the synthetic busy state (`stop_lease_holder`)."""
    env = fc.clean_hermes_env()
    existing_pp = env.get("PYTHONPATH", "")
    server_dir = fc.SERVER_DIR
    env["PYTHONPATH"] = str(server_dir) + (os.pathsep + existing_pp if existing_pp else "")
    proc = subprocess.Popen(
        [
            str(build.venv_python), str(FIXTURE_SEED), "acquire-lease",
            "--home", str(paths.home), "--profile", profile, "--session-id", session_id,
            *(["--desktop-held"] if desktop_held else []),
        ],
        env=env, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True,
    )
    assert proc.stdout is not None
    line = proc.stdout.readline()
    if not line:
        proc.wait(timeout=5)
        raise RuntimeError(f"acquire-lease exited before acquiring: {proc.returncode}")
    result = json.loads(line)
    if not result.get("ok"):
        raise RuntimeError(f"acquire-lease refused: {result}")
    return proc


def stop_lease_holder(proc: subprocess.Popen[str]) -> None:
    if proc.poll() is None:
        proc.terminate()
    try:
        proc.wait(timeout=10)
    except Exception:
        proc.kill()
        proc.wait(timeout=5)


def pair_reference_device(
    build: fc.BuildInfo, paths: fc.InstancePaths, *, port: int, user_id: str, label: str
) -> dict[str, Any]:
    """Exactly `build_fixture.py`'s own `serve_instances` reference-client pairing, called through
    the SAME `fixture_pairing_cli.py` script, unmodified."""
    common = ["--home", str(paths.home), "--xdg-state", str(paths.xdg_state)]
    endpoint = f"https://127.0.0.1:{port}"
    result = subprocess.run(
        [
            str(build.venv_python), str(FIXTURE_PAIRING_CLI), "pair-reference-client",
            *common, "--endpoint", endpoint, "--user", user_id, "--label", label,
        ],
        env=fc.clean_hermes_env(), capture_output=True, text=True, timeout=60, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"pair-reference-client failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return json.loads(result.stdout)


def build_offline(
    label: str, out: Path, *, builds_dir: str | None = None, instances: str | None = None
) -> dict[str, Any]:
    """`build_fixture.py --build <label> --out <out>` (offline; never `--serve`), unmodified, as
    its own subprocess -- exactly `test_reads_fixture.py`'s own `_build()` helper, except this one
    also captures and parses the JSON `main()` prints on the non-`--serve` path (`{"ok", "build",
    "instances": [...]}`), which carries each profile's `user_id`/`authorized` metadata this
    module needs to pair a fresh reference device without going through `--serve`. `instances`
    (comma-separated keys, e.g. `"A"`) narrows the build to just what a test needs."""
    env = dict(os.environ)
    if builds_dir:
        env["HMP_HERMES_BUILDS_DIR"] = builds_dir
    args = [sys.executable, str(BUILD_FIXTURE), "--build", label, "--out", str(out)]
    if instances:
        args += ["--instances", instances]
    result = subprocess.run(args, check=True, env=env, capture_output=True, text=True)
    info = json.loads(result.stdout)
    qualification = os.environ.get("HMP_DIRECT_SEND_QUALIFICATION")
    if qualification:
        install_fixture_qualification(
            fc.resolve_build(Path(builds_dir or env["HMP_HERMES_BUILDS_DIR"]), label),
            out, Path(qualification),
        )
    return info


def install_fixture_qualification(build: fc.BuildInfo, out: Path, qualification: Path) -> None:
    """Apply a matrix receipt ONLY to the scratch plugin copy, bound to exact current bytes.

    No environment override exists in the runtime plugin. Without a receipt, fixtures retain
    the committed fail-closed list. The matrix uses a provisional receipt after probes, then
    publishes a final receipt only after integration passes.
    """
    from hmp_plugin.compat import compute_read_bridge_fingerprint

    fc.assert_outside_real_home(out, "fixture qualification destination")
    target = out.resolve() / "_hmp_plugin" / "direct_send_supported_builds.json"
    if not target.resolve().is_relative_to(out.resolve()):
        raise fc.FixtureSafetyError("qualification destination escaped the fixture copy")
    data = json.loads(target.read_text(encoding="utf-8"))
    receipt = json.loads(qualification.read_text(encoding="utf-8"))
    if receipt.get("format") != 1 or receipt.get("bridge_files") != data["bridge_files"]:
        raise fc.FixtureSafetyError("direct-send qualification fingerprint boundary differs")
    fingerprint = compute_read_bridge_fingerprint(build.src_dir, data["bridge_files"])
    entries = [e for e in receipt.get("builds", [])
               if e.get("label") == build.label and e.get("fingerprint") == fingerprint
               and e.get("git_sha") is None and fingerprint is not None]
    if len(entries) != 1:
        raise fc.FixtureSafetyError("no exact direct-send fixture qualification for this build")
    data["builds"] = entries
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
