#!/usr/bin/env python3
"""Fixture-gateway helper for F2 direct-send integration tests (`HMP_V1.md` §7a, T-N015/T-N016).

Builds on `build_fixture.py`'s OFFLINE build (`--build <label> --out <dir>`, run unmodified as a
subprocess -- exactly like `server/tests/integration/test_reads_fixture.py`'s own `_build()`
helper; this module never imports `build_fixture.py`, so nothing here can regress F1's own fixture
tests) and ADDS, without touching that module or its output format:

  - a canonical "Bot Chat" session per profile (`fixture_seed.py seed-session --title "Bot Chat"
    --hidden`, already supports both flags -- no `fixture_seed.py` change needed);
  - `platforms.api_server` enabled on the DEFAULT profile's own `config.yaml`, bound to
    `127.0.0.1` on a fresh free port, with a synthetic >=16-char key inline (`extra.key` --
    `bridge.direct_send_endpoint`'s own DEFAULT-profile precedence, review round 2 should-fix);
  - a deterministic loopback model: the Hermes source tree's OWN e2e fixture,
    `tests/fakes/fake_llm_provider.py` (a real, stdlib-only HTTP server speaking the OpenAI Chat
    Completions wire format), loaded directly from the target BUILD's own `src_dir` via
    `importlib` (never a real provider, never a real network call) and run IN-PROCESS as a
    context manager, so every "reply" this suite ever sees is exactly `default_text` -- fully
    deterministic, per this task's own requirement.

This module owns its OWN gateway `--serve` equivalent (`start_gateway`, mirroring
`build_fixture.py`'s `serve_instances` for the HMP listener alone) rather than calling
`build_fixture.py --serve`: that function REWRITES `config.yaml` from scratch on every serve
(`_write_config_yaml(paths, profile_names, port=port)`) and would silently discard the
api_server/model blocks this module just wrote. One fixture gateway runs at a time (host load,
mirroring `test_reads_fixture.py`'s own convention) -- callers are responsible for not starting a
second one concurrently.

Everything here is additive test tooling: `fixture_seed.py`/`fixture_pairing_cli.py` are called
unmodified, through the SAME `_fixture_common.py` helpers `build_fixture.py` itself uses.
"""

from __future__ import annotations

import contextlib
import importlib.util
import json
import os
import re
import secrets
import socket
import stat
import subprocess
import sys
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

import _fixture_common as fc  # noqa: E402
import approval_fixture  # noqa: E402

FIXTURE_SEED = THIS_DIR / "fixture_seed.py"
FIXTURE_PAIRING_CLI = THIS_DIR / "fixture_pairing_cli.py"
# Fixture tooling may be invoked without pytest's server pythonpath configuration.
if str(fc.SERVER_DIR) not in sys.path:
    sys.path.insert(0, str(fc.SERVER_DIR))

BUILD_FIXTURE = THIS_DIR / "build_fixture.py"

# CS-22-style scannable prefix (mirrors `fixtures/f1/instances.yaml`'s own `label_prefix`
# discipline): a synthetic API key generated by this module always starts with this literal, so
# `tools/ci/scan_logs.py`/`private_scan_synthetic.txt`-style tooling can recognize it as fixture
# material on sight, never a real secret.
SYNTHETIC_KEY_PREFIX = "f1-fixture-apikey-"

# The canonical title `bridge.py`'s `_CANONICAL_BOT_CHAT_TITLE` selects (HMP_V1.md §7a DS-4(2)).
BOT_CHAT_TITLE = "Bot Chat"


def synthetic_api_key() -> str:
    """A clearly-synthetic, well-over-16-char `API_SERVER_KEY` (review round 2 should-fix's
    `_has_usable_secret` floor is 16; this is 18 + 24 hex chars)."""
    return SYNTHETIC_KEY_PREFIX + secrets.token_hex(12)


# --------------------------------------------------------------------------------------------------
# The deterministic loopback model (`tests/fakes/fake_llm_provider.py`, loaded from the BUILD).
# --------------------------------------------------------------------------------------------------


def load_fake_llm_provider(build: fc.BuildInfo) -> ModuleType:
    """Loads the target build's OWN `tests/fakes/fake_llm_provider.py` by file path (never a
    package import -- this module lives inside the Hermes source tree, not on this process's own
    `sys.path`, and different extracted builds must never shadow each other's copy in
    `sys.modules`). It is pure standard library (`http.server`, `threading`, `dataclasses`), so it
    imports cleanly in THIS process without needing the build's own venv or any of its
    dependencies."""
    path = build.src_dir / "tests" / "fakes" / "fake_llm_provider.py"
    if not path.is_file():
        raise fc.FixtureSafetyError(
            f"{path} not found -- this build's source tree has no e2e fake-LLM fixture "
            "(tests/fakes/fake_llm_provider.py); direct-send fixture tests need it for a "
            "deterministic model."
        )
    module_name = f"_hmp_fixture_fake_llm_provider_{build.label}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # `dataclass` (used throughout this file) resolves string annotations by looking its own
    # module up in `sys.modules[cls.__module__]` -- it must be registered there BEFORE
    # `exec_module` runs the class bodies, or that lookup raises.
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------------------------------------------
# config.yaml: api_server + model, written AFTER the offline build, never touched again by
# `build_fixture.py` (this module does its own `--serve` equivalent below).
# --------------------------------------------------------------------------------------------------


def write_direct_send_config(
    paths: fc.InstancePaths,
    profile_names: tuple[str, ...],
    *,
    hmp_port: int,
    api_server_port: int,
    api_key: str,
    model_base_url: str,
    named_profile_keys: dict[str, str] | None = None,
    direct_send_enabled: bool = True,
    owner_device_ids: tuple[str, ...] = (),
    cron_enabled: bool = False,
    model_enabled: bool = False,
    api_server_host: str = "127.0.0.1",
    approval_timeout: int = 120,
) -> None:
    """Rewrites the instance's own `config.yaml` (the SAME shape `build_fixture.py`'s
    `_write_config_yaml` writes, plus the new blocks) and appends a matching `model:` block to
    every profile's own `config.yaml` (mirroring how that same profile config already duplicates
    `gateway.multiplex_profiles: true` -- profile-scoped config does not inherit the model block
    from the home level in every build, so this module writes it in both places defensively).

    Every entry in `profile_names` is a `hermes profile create`d, NAMED profile -- a real,
    multiplexed Hermes gateway ALWAYS also serves its own built-in, unconfigured `"default"`
    profile FIRST (`served_profile_names()`, empirically confirmed against a live `stock-base`
    gateway's own `/hmp/v1/bots` roster: `[{"profile":"default",...}, {"profile":"f1-alpha",...},
    ...]`), so none of `fixtures/f1/instances.yaml`'s own profiles is ever `bridge.py`'s own
    "default" (`served[0]`) -- every one of them needs its OWN scoped `API_SERVER_KEY`
    (`.env`, review round 2 should-fix's NAMED-profile precedence), never `extra.key`. The
    DEFAULT-profile `extra.key` precedence itself has full unit coverage instead
    (`tests/unit/test_bridge.py::test_direct_send_endpoint_default_profile_prefers_extras_inline_key`).
    `api_key` here is `profile_names[0]`'s (the suite's primary target, `f1-alpha`) own scoped
    key; `named_profile_keys` covers any OTHER profile a test also needs one for (e.g. `f1-empty`,
    for the `no_bot_chat` case).

    `direct_send_enabled` (default `True`, unlike Hermes's own OD-F14/OD-F15 default -- this is
    TEST fixture wiring, not the real default) writes `platforms.hmp.extra.direct_send.enabled`;
    a test that specifically exercises the flag being off calls this again with `False` (review
    round 2 should-fix: the flag is re-read fresh per request, `adapter.py`'s
    `_read_direct_send_enabled` closure, so flipping it here and re-sending takes effect on the
    very next request -- no gateway restart needed)."""
    # The optional cron/model flags are used by the owner-controls gateway
    # case; all other direct-send fixtures keep those host features off.
    lines = [
        "plugins:\n",
        '  enabled: ["hmp"]\n',
        "gateway:\n",
        "  multiplex_profiles: true\n",
        "  profile_routes:\n",
    ]
    for name in profile_names:
        lines += [
            f'    - name: "{name}-route"\n',
            '      platform: "hmp"\n',
            f'      profile: "{name}"\n',
            f'      guild_id: "{name}"\n',
        ]
    lines += [
        "  platforms:\n",
        "    hmp:\n",
        "      enabled: true\n",
        "      extra:\n",
        '        bind: "127.0.0.1"\n',
        f"        port: {hmp_port}\n",
        f"        owner_device_ids: {json.dumps(list(owner_device_ids))}\n",
        "        direct_send:\n",
        f"          enabled: {'true' if direct_send_enabled else 'false'}\n",
    ]
    if cron_enabled:
        lines += ["        cron:\n", "          enabled: true\n"]
    if model_enabled:
        lines += ["        model_management:\n", "          enabled: true\n"]
    lines += [
        "    api_server:\n",
        "      enabled: true\n",
        "      extra:\n",
        f'        host: "{api_server_host}"\n',
        f"        port: {api_server_port}\n",
        f'        key: "{api_key}"\n',
    ]
    # Plugin platforms have no implicit hermes-hmp toolset. Without this explicit
    # selection Phone turns send no tools, and the fake provider routes them as aux.
    # Manual mode makes human approval deterministic; smart uses an auxiliary LLM.
    model_block = [
        "platform_toolsets:\n",
        "  hmp: [terminal, clarify]\n",
        "approvals:\n",
        "  mode: manual\n",
        f"  timeout: {int(approval_timeout)}\n",
        "  unattended_mode: deny\n",
        "terminal:\n",
        f"  cwd: {json.dumps(str(paths.out_dir))}\n",
        "model:\n",
        "  provider: custom\n",
        f"  base_url: {model_base_url}\n",
        f"  default: {_FAKE_MODEL_ID}\n",
        "  context_length: 128000\n",
        "agent:\n",
        "  api_max_retries: 1\n",
    ]
    (paths.home / "config.yaml").write_text("".join(lines + model_block), encoding="utf-8")
    (paths.home / ".env").write_text("OPENAI_API_KEY=sk-fixture-fake\n", encoding="utf-8")
    # `bridge.direct_send_endpoint`'s `api_server_extra()`/`scoped_api_server_key()` calls run
    # INSIDE `profile_runtime_scope(profile_home)` for EVERY profile (`bridge.py`'s `home = self.
    # _profile_home(profile)` is unconditional) -- and a profile-scoped `load_gateway_config()`
    # reads that profile's OWN `config.yaml`, with NO automatic inheritance from the instance
    # home's copy (empirically confirmed against a live `stock-base` gateway; mirrors the exact
    # reason `build_fixture.py` already duplicates `gateway.multiplex_profiles: true` at both
    # levels). Every profile therefore needs its own copy of the `platforms.api_server.extra`
    # block (host/port only -- `key` never goes here; see the docstring above).
    for name in profile_names:
        profile_cfg = paths.home / "profiles" / name / "config.yaml"
        profile_lines = [
            "gateway:\n",
            "  multiplex_profiles: true\n",
            "  platforms:\n",
            "    api_server:\n",
            "      enabled: true\n",
            "      extra:\n",
            f'        host: "{api_server_host}"\n',
            f"        port: {api_server_port}\n",
        ]
        profile_cfg.write_text("".join(profile_lines + model_block), encoding="utf-8")
    all_keys = {profile_names[0]: api_key, **(named_profile_keys or {})}
    write_named_profile_keys(paths, all_keys)


def write_named_profile_keys(paths: fc.InstancePaths, named_profile_keys: dict[str, str]) -> None:
    """A NAMED (non-default) profile's own `API_SERVER_KEY`, via that profile's own `.env`
    (`profiles/<name>/.env`) -- `bridge.direct_send_endpoint` never reads a named profile's
    `extra.key` (review round 2 should-fix: only the DEFAULT profile does), only its own scoped
    secret, exactly mirroring `api_server.py`'s own `_expected_api_key` precedence for a non-
    default profile. Written (or re-written) independently of `write_direct_send_config`'s own
    call, so a test can add a key for a profile it did not know about at fixture-build time."""
    for name, key in named_profile_keys.items():
        profile_dir = paths.home / "profiles" / name
        profile_dir.mkdir(parents=True, exist_ok=True)
        (profile_dir / ".env").write_text(f"API_SERVER_KEY={key}\n", encoding="utf-8")


def remove_named_profile_key(paths: fc.InstancePaths, profile: str) -> None:
    """Drops a NAMED profile's scoped `API_SERVER_KEY` (its fixture-written `.env`), leaving the
    instance-level `platforms.api_server.extra.key` in place. A named profile must NOT fall back to
    that shared key; this lets a test prove it."""
    (paths.home / "profiles" / profile / ".env").unlink(missing_ok=True)


# --------------------------------------------------------------------------------------------------
# Test-only jobs admission. `mobile_cron.qualified_build()` is a production gate: it passes only
# for a build whose cron fingerprint is listed in `mobile_cron_supported_builds.json`. A fixture
# against a build with no such entry (for example a candidate Hermes not yet qualified) therefore
# stays closed. This edits ONLY the fixture's scratch plugin copy (`build_fixture.py`'s
# `_hmp_plugin`), never `server/hmp_plugin`, and is never a production qualification.
# --------------------------------------------------------------------------------------------------

JOBS_TEST_ADMISSION_LABEL = "fixture-test-only-jobs-admission"


def scratch_plugin_dir(paths: fc.InstancePaths) -> Path:
    """The scratch plugin copy this instance loads, refused unless it lives under `--out` and
    outside the tracked `server/` tree."""
    real = (paths.home / "plugins" / "hmp").resolve()
    if paths.out_dir.resolve() not in real.parents or fc.SERVER_DIR.resolve() in (
        real, *real.parents,
    ):
        raise fc.FixtureSafetyError(f"refusing to edit a non-scratch plugin directory: {real}")
    return real


def set_jobs_test_admission(
    build: fc.BuildInfo, paths: fc.InstancePaths, *, admitted: bool
) -> None:
    """Set the scratch copy's cron manifest to exactly one test-only entry (`admitted`) or to no
    entries at all (closed, even where the production manifest would list the build). Re-read on
    every request, so no gateway restart is needed. The entry binds to the fingerprint and git SHA
    of THIS build's own 11 cron-manifest files, computed by the same `GitFingerprintReader` the
    gate uses; it is not evidence about any native callee outside those files."""
    manifest = scratch_plugin_dir(paths) / "mobile_cron_supported_builds.json"
    data = json.loads(manifest.read_text(encoding="utf-8"))
    data["builds"] = []
    if admitted:
        if str(fc.SERVER_DIR) not in sys.path:
            sys.path.insert(0, str(fc.SERVER_DIR))
        from hmp_plugin import compat

        identity = compat.GitFingerprintReader(data["bridge_files"]).read(build.src_dir)
        if identity is None:
            raise fc.FixtureSafetyError(f"build {build.label!r}: cron files not fingerprintable")
        data["builds"].append({
            "label": JOBS_TEST_ADMISSION_LABEL,
            "fingerprint": identity.fingerprint,
            "git_sha": identity.git_sha,
            "qualified_by": "test-only scratch admission; not a production qualification",
            "qualified_at": "fixture",
        })
    manifest.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------------------------------
# Opt-in candidate build label. Collection only: this reads directory names, never imports or runs
# Hermes. Mirrors `test_reads_fixture.py`'s `HMP_COMPAT_CANDIDATE_LABEL` rule (not a default label,
# its `src` extracted), plus a harmless-name check so the value can never be a path.
# --------------------------------------------------------------------------------------------------

CANDIDATE_LABEL_ENV = "HMP_DIRECT_SEND_CANDIDATE_LABEL"
_CANDIDATE_LABEL_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}")


def candidate_build_labels(
    candidate: str, builds_dir: str, defaults: tuple[str, ...]
) -> tuple[str, ...]:
    """`(candidate,)` only for an exact harmless label that is not already a default build and whose
    `<builds_dir>/<label>/src` exists; otherwise `()`.
    The default labels are never aliased to it."""
    if (
        not candidate
        or not builds_dir
        or candidate in defaults
        or _CANDIDATE_LABEL_RE.fullmatch(candidate) is None
        or ".." in candidate
        or not (Path(builds_dir) / candidate / "src").is_dir()
    ):
        return ()
    return (candidate,)


_FAKE_MODEL_ID = "fake-model"  # `tests.fakes.fake_llm_provider.MODEL_ID`, mirrored as a literal
# (never imported at module scope -- the module itself is loaded lazily, per build, above).


# --------------------------------------------------------------------------------------------------
# The canonical "Bot Chat" (DS-4(2)): title exactly "Bot Chat", hidden, at least one row so
# `head_message_id` is a real int (`expected_head: null` is `400 bad_request`, DS-1 -- a brand-new,
# zero-message Bot Chat cannot be targeted by this route at all; out of scope for this fixture,
# which always seeds at least one exchange).
# --------------------------------------------------------------------------------------------------


def seed_bot_chat(
    build: fc.BuildInfo,
    paths: fc.InstancePaths,
    profile: str,
    session_id: str,
    *,
    messages: list[dict[str, str]] | None = None,
) -> None:
    messages = messages if messages is not None else [
        {"role": "user", "content": "fixture seed: hello"},
        {"role": "assistant", "content": "fixture seed: hi there"},
    ]
    tmp_dir = paths.out_dir / "direct_send_seed"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    messages_file = tmp_dir / f"{profile}-{session_id}-bot-chat.json"
    messages_file.write_text(json.dumps(messages), encoding="utf-8")
    fc.run_seed_script(
        build,
        FIXTURE_SEED,
        "seed-session",
        "--home", str(paths.home),
        "--profile", profile,
        "--session-id", session_id,
        "--source", "desktop",
        "--title", BOT_CHAT_TITLE,
        "--hidden",
        "--messages-file", str(messages_file),
    )


# --------------------------------------------------------------------------------------------------
# The gateway process itself (mirrors `build_fixture.serve_instances`' HMP-listener spawn, minus
# the reference-device pairing this module's own tests do differently -- see the test module).
# --------------------------------------------------------------------------------------------------


def wait_for_port(port: int, *, timeout: float) -> bool:
    """Legacy generic TCP wait for callers that own no process. The native gateway starts use
    `require_native_listener`, which also watches the spawned process."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            try:
                s.connect(("127.0.0.1", port))
            except OSError:
                time.sleep(0.5)
                continue
            return True
    return False


# The one hard deadline for a native HMP listener, from spawn. Unchanged from the former
# `wait_for_port(..., timeout=45.0)` calls; nothing below extends or resets it.
NATIVE_LISTENER_DEADLINE_SECONDS = 45.0
_CONNECT_TIMEOUT_SECONDS = 1.0
_RETRY_SLEEP_SECONDS = 0.5
NATIVE_START_RECORD = "native_start_readiness.jsonl"
NATIVE_START_PHASES = ("first_start", "restart")
_LOG_TAIL_CHARS = 4000


@dataclass(frozen=True)
class ReadinessResult:
    """Content-free outcome of one native listener wait. `outcome` is exactly one of `ready`,
    `process_exit` or `deadline`; `exit_code` is set only for `process_exit`."""

    outcome: str
    elapsed: float
    attempts: int
    exit_code: int | None = None


class NativeStartError(RuntimeError):
    """A native gateway start that did not reach readiness. `classification` is `process_exit`
    or `deadline`; the new metadata in the message (phase, exit code, deadline) is content-free.
    The message also carries the existing, unredacted local gateway log tail the fixture has
    always emitted (bounded, private fixture material, not a public artifact)."""

    classification = "native_start"

    def __init__(self, message: str, result: ReadinessResult) -> None:
        super().__init__(message)
        self.result = result


class NativeProcessExitError(NativeStartError):
    classification = "process_exit"


class NativeListenerDeadlineError(NativeStartError):
    classification = "deadline"


def _connect_loopback(port: int, timeout: float) -> None:
    """One loopback TCP connect. Raises OSError (incl. timeout) on failure."""
    with socket.create_connection(("127.0.0.1", port), timeout=timeout):
        pass


def wait_for_native_listener(
    proc: subprocess.Popen[bytes],
    port: int,
    *,
    timeout: float = NATIVE_LISTENER_DEADLINE_SECONDS,
    clock: Callable[[], float] = time.monotonic,
    sleep: Callable[[float], None] = time.sleep,
    connect: Callable[[int, float], None] | None = None,
) -> ReadinessResult:
    """Process-aware readiness: the SAME loopback TCP connect as `wait_for_port`, under one hard
    monotonic deadline measured from this call (the caller invokes it right after spawn), no
    sliding extension.

    The exact spawned `proc` is polled before each connect and again after a connect succeeds; an
    exited process is `process_exit` immediately, so a listener that appears on the port while
    `proc` is dead (or belongs to something else) never qualifies. After that poll the deadline is
    checked once more: a connect that succeeds at or after it is `deadline`, not `ready`. Each
    connect timeout and each sleep is clamped to the time left, so requested waits cannot exceed
    `timeout`; the OS may still return later than requested, but no success at or after the
    ceiling can qualify. This is readiness only, not listener ownership or authority: pairing/TLS
    and the later gates stay authoritative. A connect failure of any kind counts as not ready."""
    # The deadline is a ceiling, never widened: a caller may only shorten it.
    if not 0 <= timeout <= NATIVE_LISTENER_DEADLINE_SECONDS:
        raise ValueError("native listener timeout must be within 0..45 seconds")
    connect = connect or _connect_loopback
    start = clock()
    deadline = start + timeout
    attempts = 0

    def result(outcome: str, code: int | None = None, now: float | None = None) -> ReadinessResult:
        return ReadinessResult(
            outcome, max(0.0, (clock() if now is None else now) - start), attempts, code
        )

    while True:
        code = proc.poll()
        if code is not None:
            return result("process_exit", code)
        remaining = deadline - clock()
        if remaining <= 0:
            return result("deadline")
        attempts += 1
        try:
            connect(port, min(_CONNECT_TIMEOUT_SECONDS, remaining))
        except OSError:
            connected = False
        else:
            connected = True
        if connected:
            # The connect may have reached a listener that is not this process's.
            code = proc.poll()
            if code is not None:
                return result("process_exit", code)
            # A connect that returns at or after the ceiling (a last-moment success, or the OS
            # delaying this thread) never qualifies; the clock is read after the poll so a slow
            # poll counts too. One read serves both the check and the reported elapsed.
            now = clock()
            if now >= deadline:
                return result("deadline", now=now)
            return result("ready", now=now)
        remaining = deadline - clock()
        if remaining <= 0:
            continue  # the top-of-loop poll decides process_exit before deadline
        sleep(min(_RETRY_SLEEP_SECONDS, remaining))


def _require_known_phase(phase: str) -> None:
    if phase not in NATIVE_START_PHASES:
        raise ValueError(f"native start phase must be one of {NATIVE_START_PHASES}")


def record_native_start(out_dir: Path, phase: str, result: ReadinessResult) -> None:
    """Appends one minimal line to the fixture artifact: phase, outcome, elapsed seconds, attempt
    count and exit code. No environment, argv, prompt, key, identifier or transcript."""
    line = {
        "phase": phase,
        "outcome": result.outcome,
        "elapsed_seconds": round(result.elapsed, 3),
        "attempts": result.attempts,
        "exit_code": result.exit_code,
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    with (out_dir / NATIVE_START_RECORD).open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(line, sort_keys=True) + "\n")


def require_native_listener(
    proc: subprocess.Popen[bytes],
    port: int,
    *,
    phase: str,
    out_dir: Path,
    log_path: Path,
    timeout: float = NATIVE_LISTENER_DEADLINE_SECONDS,
    **boundaries: Any,
) -> ReadinessResult:
    """`wait_for_native_listener`, recorded for `phase` (`first_start` or `restart`); raises a
    classified `NativeStartError` (with the local log tail, as before) unless ready."""
    _require_known_phase(phase)
    result = wait_for_native_listener(proc, port, timeout=timeout, **boundaries)
    record_native_start(out_dir, phase, result)
    if result.outcome == "ready":
        return result
    tail = log_path.read_text(encoding="utf-8", errors="replace")[-_LOG_TAIL_CHARS:]
    if result.outcome == "process_exit":
        raise NativeProcessExitError(
            f"{phase}: gateway process exited (code {result.exit_code}) before the HMP "
            f"listener was ready.\nLog tail:\n{tail}",
            result,
        )
    raise NativeListenerDeadlineError(
        f"{phase}: HMP listener did not come up within {timeout:g}s.\nLog tail:\n{tail}",
        result,
    )


def start_gateway(
    build: fc.BuildInfo, paths: fc.InstancePaths, *, log_path: Path
) -> subprocess.Popen[bytes]:
    fc.assert_instance_paths_safe(paths)
    hermes_bin = build.venv_python.parent / "hermes"
    env = fc.clean_hermes_env(
        extra={"HERMES_HOME": str(paths.home), "XDG_STATE_HOME": str(paths.xdg_state)}
    )
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = log_path.open("w", encoding="utf-8")
    return subprocess.Popen(
        [str(hermes_bin), "gateway", "run", "--force"],
        env=env, stdout=log_file, stderr=subprocess.STDOUT,
    )


def stop_gateway(proc: subprocess.Popen[bytes]) -> None:
    if proc.poll() is None:
        proc.terminate()
    try:
        proc.wait(timeout=15)
    except Exception:
        proc.kill()
        proc.wait(timeout=5)


def start_native_gateway(
    build: fc.BuildInfo,
    paths: fc.InstancePaths,
    *,
    port: int,
    phase: str,
    log_path: Path,
) -> subprocess.Popen[bytes]:
    """Spawns the gateway and waits for its listener under the process-aware deadline. On any
    failure the spawned process is stopped before the classified error propagates, so a caller
    never inherits (or leaks) a half-started process."""
    _require_known_phase(phase)  # before any spawn
    proc = start_gateway(build, paths, log_path=log_path)
    try:
        require_native_listener(
            proc, port, phase=phase, out_dir=paths.out_dir, log_path=log_path
        )
    except BaseException:
        stop_gateway(proc)
        raise
    return proc


def start_lease_holder(
    build: fc.BuildInfo,
    paths: fc.InstancePaths,
    *,
    profile: str,
    session_id: str,
    desktop_held: bool = False,
) -> subprocess.Popen[str]:
    """Starts `fixture_seed.py acquire-lease` as a BACKGROUND process that holds the lease for as
    long as it stays alive (see that command's own docstring for why it must not exit). Blocks
    briefly here only to confirm the one JSON result line, so a caller never races the lease's own
    acquisition. The caller is responsible for terminating the returned process once the test no
    longer wants the synthetic busy state (`stop_lease_holder`)."""
    env = fc.clean_hermes_env()
    existing_pp = env.get("PYTHONPATH", "")
    server_dir = fc.SERVER_DIR
    env["PYTHONPATH"] = str(server_dir) + (os.pathsep + existing_pp if existing_pp else "")
    proc = subprocess.Popen(
        [
            str(build.venv_python), str(FIXTURE_SEED), "acquire-lease",
            "--home", str(paths.home), "--profile", profile, "--session-id", session_id,
            *(["--desktop-held"] if desktop_held else []),
        ],
        env=env, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True,
    )
    assert proc.stdout is not None
    line = proc.stdout.readline()
    if not line:
        proc.wait(timeout=5)
        raise RuntimeError(f"acquire-lease exited before acquiring: {proc.returncode}")
    result = json.loads(line)
    if not result.get("ok"):
        raise RuntimeError(f"acquire-lease refused: {result}")
    return proc


def stop_lease_holder(proc: subprocess.Popen[str]) -> None:
    if proc.poll() is None:
        proc.terminate()
    try:
        proc.wait(timeout=10)
    except Exception:
        proc.kill()
        proc.wait(timeout=5)


def pair_reference_device(
    build: fc.BuildInfo, paths: fc.InstancePaths, *, port: int, user_id: str, label: str,
    grant_owner_controls: bool = False,
) -> dict[str, Any]:
    """Pair a fixture device through the real host CLI in an isolated home.

    The default explicitly declines owner controls. Set `grant_owner_controls`
    only when the test is checking that separate host decision.
    """
    common = ["--home", str(paths.home), "--xdg-state", str(paths.xdg_state)]
    endpoint = f"https://127.0.0.1:{port}"
    result = subprocess.run(
        [
            str(build.venv_python), str(FIXTURE_PAIRING_CLI), "pair-reference-client",
            *common, "--endpoint", endpoint, "--user", user_id, "--label", label,
            *(["--grant-owner-controls"] if grant_owner_controls else []),
        ],
        env=fc.clean_hermes_env(), capture_output=True, text=True, timeout=60, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"pair-reference-client failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return json.loads(result.stdout)


# The offline build needs only a runnable toolchain: `build_fixture.py` and every child it spawns
# (`hermes profile create`, the seed scripts, git) re-derive HERMES_*/XDG_* themselves, and nothing
# under tools/fixtures or server/hmp_plugin reads another variable. The caller's credentials and
# Hermes/live-home variables are therefore NOT forwarded. `PYTHONDONTWRITEBYTECODE` is the matrix's
# own test control; `HMP_HERMES_BUILDS_DIR` is added explicitly from `builds_dir`. The receipt
# variables (`HMP_DIRECT_SEND_QUALIFICATION`, `RECEIPT_ENV`) are read by THIS process after the
# build and are never needed, or forwarded, to it.
BUILD_ENV_ALLOWLIST = (
    "PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "LC_CTYPE", "PYTHONDONTWRITEBYTECODE",
)
BUILD_FAILURE_OUTPUT = "build_offline_failure.log"
BUILD_FAILURE_STREAM_CAP = 64 * 1024  # bytes kept per stream (the tail); the rest is dropped


def offline_build_env(builds_dir: str | None) -> dict[str, str]:
    env = {k: os.environ[k] for k in BUILD_ENV_ALLOWLIST if k in os.environ}
    builds = builds_dir or os.environ.get("HMP_HERMES_BUILDS_DIR")
    if builds:
        env["HMP_HERMES_BUILDS_DIR"] = builds
    return env


# Only the two known macOS aliases are normalized (`/tmp` -> `/private/tmp`, `/var` ->
# `/private/var`), and only while the alias really is a root-owned symlink with exactly that
# target. Any other symlink in the path is refused, never resolved.
_PLATFORM_ALIASES = {"/tmp": "private/tmp", "/var": "private/var"}  # noqa: S108 - alias table
_DIR_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
# The one sticky shared directory an ancestor may be: the root-owned temp base, by canonical name.
_SHARED_TEMP_BASES = ("/private/tmp", "/tmp")  # noqa: S108 - the known shared temp base
BUILD_FAILURE_NOT_RETAINED = ("not_retained_unsafe_destination", "not_retained_write_failed")


def _normalize_platform_alias(path: str) -> str:
    for alias, target in _PLATFORM_ALIASES.items():
        if path == alias or path.startswith(alias + "/"):
            try:
                st = os.lstat(alias)
                if stat.S_ISLNK(st.st_mode) and st.st_uid == 0 and os.readlink(alias) == target:
                    return "/" + target + path[len(alias):]
            except OSError:
                pass
            break
    return path


def _ancestor_is_trusted(st: os.stat_result, canonical: str) -> bool:
    """An ancestor may only be renamed/replaced by its owner, so it must be owned by root or this
    user and not group/other-writable. The one exception is the known shared temp base, accepted
    only when its real metadata is a root-owned sticky directory; no other sticky or foreign
    directory is trusted."""
    if not stat.S_ISDIR(st.st_mode):
        return False
    if canonical in _SHARED_TEMP_BASES:
        return st.st_uid == 0 and bool(st.st_mode & stat.S_ISVTX)
    if st.st_uid not in (0, os.geteuid()):
        return False
    return not st.st_mode & (stat.S_IWGRP | stat.S_IWOTH)


def _open_private_output_dir(out: Path) -> int | None:
    """Returns a directory fd for `out`, or None when it is not a safe private destination.

    The absolute path is walked one component at a time with `openat(O_NOFOLLOW|O_DIRECTORY)` from
    `/`, so a symlink in ANY component (not just the last) is refused and nothing is resolved. Only
    the final component may be created (mode 0700, never `parents=True`, nothing else is made or
    chmod-ed); its parent must already exist. Every ancestor must be owned by root or this user and
    not group/other-writable (the root-owned sticky temp base excepted), so no one else can rename
    the directory out from under the path. The final directory must be owned by this user with
    mode exactly 0700. The caller keeps the fd, so a later write goes to this inode, never to
    whatever the path names afterwards."""
    try:
        fc.assert_outside_real_home(out, "fixture build output")
        raw = os.fspath(out)
        if not os.path.isabs(raw):
            raw = os.path.join(os.getcwd(), raw)
        parts = [p for p in _normalize_platform_alias(raw).split("/") if p not in ("", ".")]
        if not parts or ".." in parts:
            return None
        fd = os.open("/", _DIR_FLAGS)
        try:
            if not _ancestor_is_trusted(os.fstat(fd), "/"):
                raise OSError
            for i, name in enumerate(parts):
                try:
                    nxt = os.open(name, _DIR_FLAGS, dir_fd=fd)
                except FileNotFoundError:
                    if i != len(parts) - 1:
                        raise
                    os.mkdir(name, 0o700, dir_fd=fd)
                    nxt = os.open(name, _DIR_FLAGS, dir_fd=fd)
                os.close(fd)
                fd = nxt
                if i != len(parts) - 1 and not _ancestor_is_trusted(
                    os.fstat(fd), "/" + "/".join(parts[: i + 1])
                ):
                    raise OSError
            st = os.fstat(fd)
            if st.st_uid != os.geteuid() or stat.S_IMODE(st.st_mode) != 0o700:
                raise OSError
        except BaseException:
            os.close(fd)
            raise
        return fd
    except (OSError, ValueError, fc.FixtureSafetyError):
        return None


def _retain_build_failure_output(dir_fd: int | None, stdout: bytes, stderr: bytes) -> str:
    """Writes the build's raw output (unfiltered, tail-bounded) into the private directory behind
    `dir_fd` as a new 0600 file and returns a closed status word; it never raises. The file is
    created `O_EXCL|O_NOFOLLOW` relative to the fd, so it cannot be redirected or replace anything.
    On a write/close failure the partial file is unlinked only if the name still refers to the
    inode this call created (checked against the open fd); a failed cleanup is not retried and
    nothing about the failure (exception text, paths) is returned or kept. The raw output is
    fixture-private diagnostic material for the root reviewer and is never put in an exception."""
    if dir_fd is None:
        return BUILD_FAILURE_NOT_RETAINED[0]
    try:
        st = os.fstat(dir_fd)
        if st.st_uid != os.geteuid() or stat.S_IMODE(st.st_mode) != 0o700:
            return BUILD_FAILURE_NOT_RETAINED[0]
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
        fd = os.open(BUILD_FAILURE_OUTPUT, flags, 0o600, dir_fd=dir_fd)
    except OSError:
        return BUILD_FAILURE_NOT_RETAINED[0]
    status = "retained"
    created = None
    try:
        created = os.fstat(fd)
        parts = []
        for name, data in (("stdout", stdout), ("stderr", stderr)):
            kept = data[-BUILD_FAILURE_STREAM_CAP:]
            parts.append(f"== {name}: {len(data)} bytes, last {len(kept)} kept ==\n".encode())
            parts.append(kept + b"\n")
        view = memoryview(b"".join(parts))
        while view:
            written = os.write(fd, view)
            if type(written) is not int or not 0 < written <= len(view):
                raise OSError  # no progress (or nonsense): closed, never retried or spun on
            view = view[written:]
    except Exception:  # a diagnostic must never replace the native failure
        status = BUILD_FAILURE_NOT_RETAINED[1]
    try:
        os.close(fd)
    except Exception:
        status = BUILD_FAILURE_NOT_RETAINED[1]
    if status != "retained" and created is not None:
        with contextlib.suppress(Exception):  # one attempt; a failed cleanup is not retried
            now = os.stat(BUILD_FAILURE_OUTPUT, dir_fd=dir_fd, follow_symlinks=False)
            if (now.st_dev, now.st_ino) == (created.st_dev, created.st_ino):
                os.unlink(BUILD_FAILURE_OUTPUT, dir_fd=dir_fd)
    return status


def build_offline(
    label: str, out: Path, *, builds_dir: str | None = None, instances: str | None = None
) -> dict[str, Any]:
    """`build_fixture.py --build <label> --out <out>` (offline; never `--serve`) as its own
    subprocess, plus `--private-seed-diagnostics` -- exactly `test_reads_fixture.py`'s own
    `_build()` helper, except this one also captures and parses the JSON `main()` prints on
    the non-`--serve` path (`{"ok", "build", "instances": [...]}`), which carries each
    profile's `user_id`/`authorized` metadata this module needs to pair a fresh reference
    device without going through `--serve`. `instances` (comma-separated keys, e.g. `"A"`)
    narrows the build to just what a test needs.

    `--private-seed-diagnostics` makes the `seed-messages` child dump one nonfatal all-thread
    Python stack to its stderr if it is still running after 90 s. That stderr is sensitive and
    reaches only this helper's private capture (retained 0600 on failure, never in the error or
    the pytest report); a caller invoking `build_fixture.py` directly with the flag must capture
    stderr privately too.

    The child gets `offline_build_env`, not the caller's environment. A nonzero exit raises a
    closed `FixtureSafetyError` (phase and exit code only: no argv, environment or output) and the
    raw output is kept only in `BUILD_FAILURE_OUTPUT` under `out`, mode 0600, when `out` is a
    private (0700, this user's) directory reached without a symlink. So does a zero exit whose
    stdout is not one JSON object (the body is never in the error). Never retried.

    An `out` that is not such a destination (symlinked ancestor, missing parent, `..`, wrong owner
    or mode) is refused BEFORE any child is started, with a closed `FixtureSafetyError`
    (`phase=build_offline_destination`, no path); nothing is created or chmod-ed for it."""
    env = offline_build_env(builds_dir)
    args = [sys.executable, str(BUILD_FIXTURE), "--build", label, "--out", str(out)]
    if instances:
        args += ["--instances", instances]
    # Private output is arranged BEFORE the build (created 0700 if absent, nothing else made or
    # chmod-ed) and the fd is held, so a failure is retained into that same inode.
    out_fd = _open_private_output_dir(Path(out))
    if out_fd is None:
        raise fc.FixtureSafetyError(
            "offline fixture build refused: phase=build_offline_destination "
            "private_output=not_retained_unsafe_destination"
        ) from None
    # Only after the private destination is held: stderr may then carry a diagnostic stack.
    args.append("--private-seed-diagnostics")
    failure: str | None = None
    try:
        result = subprocess.run(args, check=False, env=env, capture_output=True)
        info = None
        if result.returncode == 0:
            # Parsed inline, not through a helper taking the body: pytest's long traceback prints
            # each frame's arguments, so `json.loads(s=<child stdout>)` would put the body in a
            # failure report. Only flagged here; the raise is outside any except block.
            with contextlib.suppress(ValueError):
                info = json.loads(result.stdout.decode("utf-8"))
            if not isinstance(info, dict):
                failure = (
                    f"phase=build_offline_output exit_code=0 stdout_bytes={len(result.stdout)}"
                )
        else:
            failure = f"phase=build_offline exit_code={result.returncode}"
        if failure is not None:
            retained = _retain_build_failure_output(out_fd, result.stdout, result.stderr)
    finally:
        with contextlib.suppress(OSError):  # owned fd only; never replaces the native result
            os.close(out_fd)
    if failure is not None:
        raise fc.FixtureSafetyError(
            f"offline fixture build failed: {failure} private_output={retained}"
        ) from None
    qualification = os.environ.get("HMP_DIRECT_SEND_QUALIFICATION")
    approval_receipt = os.environ.get(approval_fixture.RECEIPT_ENV)
    if qualification or approval_receipt:
        builds = builds_dir or os.environ["HMP_HERMES_BUILDS_DIR"]
        build = fc.resolve_build(Path(builds), label)
        if qualification:
            install_fixture_qualification(build, out, Path(qualification))
        # A separate lane, manifest and receipt: the direct-send receipt above never opens it.
        approval_fixture.install_from_env(build, out, approval_receipt)
    return info


def install_fixture_qualification(build: fc.BuildInfo, out: Path, qualification: Path) -> None:
    """Apply a matrix receipt ONLY to the scratch plugin copy, bound to exact current bytes.

    No environment override exists in the runtime plugin. Without a receipt, fixtures retain
    the committed fail-closed list. The matrix uses a provisional receipt after probes, then
    publishes a final receipt only after integration passes.
    """
    from hmp_plugin.compat import compute_read_bridge_fingerprint, load_read_compat_list

    fc.assert_outside_real_home(out, "fixture qualification destination")
    target = out.resolve() / "_hmp_plugin" / "direct_send_supported_builds.json"
    if not target.resolve().is_relative_to(out.resolve()):
        raise fc.FixtureSafetyError("qualification destination escaped the fixture copy")
    data = json.loads(target.read_text(encoding="utf-8"))
    receipt = json.loads(qualification.read_text(encoding="utf-8"))
    if receipt.get("format") != 1 or receipt.get("bridge_files") != data["bridge_files"]:
        raise fc.FixtureSafetyError("direct-send qualification fingerprint boundary differs")
    # Validate with the actual runtime parser before changing the fixture. Identity-only
    # candidates lack BuildEntry provenance and would silently close the runtime gate.
    try:
        load_read_compat_list(qualification)
    except (TypeError, ValueError) as exc:
        raise fc.FixtureSafetyError("invalid direct-send fixture qualification schema") from exc
    fingerprint = compute_read_bridge_fingerprint(build.src_dir, data["bridge_files"])
    # An archive (no .git) needs a fingerprint-only entry; a git-install fixture needs one bound to
    # the build's own HEAD, exactly as the runtime matches them. `None == None` for an archive.
    head = approval_fixture.independent_git_head(build.src_dir)
    entries = [e for e in receipt.get("builds", [])
               if e.get("label") == build.label and e.get("fingerprint") == fingerprint
               and e.get("git_sha") == head and fingerprint is not None]
    if len(entries) != 1:
        raise fc.FixtureSafetyError("no exact direct-send fixture qualification for this build")
    data["builds"] = entries
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
